apiVersion: apps/v1
kind: Deployment
metadata:
  name: hasher
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hasher
  template:
    metadata:
      labels:
        app: hasher
    spec:
      containers:
      - name: hasher
        image: igorarizacuemby/hasher:latest
        ports: 
        - containerPort: 80
        