apiVersion: apps/v1
kind: Deployment
metadata:
  name: rng
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rng
  template:
    metadata:
      labels:
        app: rng
    spec:
      containers:
      - name: rng
        image: igorarizadevelop/rng:latest
        ports: 
        - containerPort: 80
        